### PR TITLE
Fix in 2018, update dependencies.

### LINKED ISSUE #4: cargo-wa outdated, doesn't run on nightly anymore
needs updating to `cargo-wasm`

### PR DESCRIPTION
**Pull request by qm3ster**
Mostly:
- replaces `cargo-wa` with working `cargo-wasm`
- add a server so that loading wasm doesn't require setting browser security flags
closes #4

### CODE REVIEW

**Comment by qm3ster** [comment]
Henlo @couchand

**Comment by couchand** [comment]
Awesome stuff, thanks!  Can you `add -D` prettier please?

**Comment by qm3ster** [comment]
Sure, when I get to a pc.
It's not in any hooks or anything, but I get the reason behind having a bundled version.

**Comment by qm3ster** [comment]
@couchand done

**Comment by couchand** [comment]
Thanks for adding that.  Unfortunately, the latest commit seems to break for me: `TypeError: invalid assignment to const `e'`...

And in the course of investigating where that was coming from, I noticed that `make clean && make` got broken by the change to move the build artifacts to `dist` instead of `site`.

Could you perhaps open a PR with just the focused changes?  All the extra stuff (moving files around, etc) just seems like churn.  If that's too much work I can just cherry-pick the first few commits...

**Comment by couchand** [comment]
Also, I really appreciate your enthusiasm here!  I hope I'm not dampening it, just focusing it.

**Comment by qm3ster** [comment]
I can make a more targeted PR if you can list which of the changes (by commit name) you'd like to incorporate.
I moved the sources and the build artifacts because webpack has defaults for those now, and it's better to not deviate from defaults needlessly. Maybe I should leave it as it is though.
Do you want this repo to be Typescript on master or not?

**Comment by couchand** [comment]
I guess everything except the last commit will do.  I can't immediately see what's wrong with the last commit, but there's no reason to block the rest on it.  Using the webpack defaults makes sense, it's too bad that cargo-wasm can't be configured for a different target (maybe worth an upstream PR I guess?).  I don't understand the motivation behind moving the readme and slightly editing the formatting but I won't quibble over it.  Let's get this merged!

Re: Typescript, I think more exploration is necessary to make sure that it enhances the example.  Let's keep discussing it on #6 or #2 to see if we can find a good answer.

**Comment by couchand** [comment]
Hey, that PR to cargo-wasm didn't turn out to be very hard!  mgattozzi/cargo-wasm#14

**Comment by couchand** [comment]
Merged all but the last commit, not sure what's going on with that one.

**Pull request closed without merging**
